# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Home
email: singh[dot]amitesh[at]gmail.com
description: Log about stuffs related to electronics and software.

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://amitesh-singh.github.io" # the base hostname & protocol for your site
twitter_username: amitesh_singh
github_username:  amitesh-singh

# Build settings
markdown: kramdown

theme: jekyll-theme-midnight

